language: node_js
node_js: 12.16.2
before_script:
  - git checkout master

script:
  - npm install
  - npm build

cache:
  yarn: true
  webpack: true
  directories:
    - "node_modules"  

  
env:
 global:
   - GH_REF: github.com/purinpurin/Durian.git